name: CI/CD para LoopifyFinal

env:
  AZURE_WEBAPP_NAME: loopify-app-631               # Nombre de tu App Service
  DOTNET_VERSION: '4.8'

on:
  push:
    branches:
      - main
    paths:
      - 'LoopifyFinal/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
      
      - name: Instalar .NET Framework y MSBuild
        run: |
          choco install microsoft-build-tools -y
          choco install netfx-4.8-devpack -y
          choco install visualstudio2019buildtools -y
          choco install nuget.commandline -y

      - name: Restaurar dependencias
        run: |
          cd LoopifyFinal
          nuget restore LoopifyFinal.sln

      - name: Compilar la solución
        run: |
          cd LoopifyFinal
          msbuild LoopifyFinal.sln /p:Configuration=Release

      - name: Publicar la aplicación
        run: |
          cd LoopifyFinal
          msbuild LoopifyFinal.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:OutputPath=../publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Desplegar a Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./LoopifyFinal/publish
